// Nepal provinces
export const nepalProvinces = [
  { id: "1", name: "Koshi Province" },
  { id: "2", name: "Madhesh Province" },
  { id: "3", name: "Bagmati Province" },
  { id: "4", name: "Gandaki Province" },
  { id: "5", name: "Lumbini Province" },
  { id: "6", name: "Karnali Province" },
  { id: "7", name: "Sudurpashchim Province" },
];

// Districts by province
export const districtsByProvince: Record<string, string[]> = {
  "1": [
    "Taplejung",
    "Panchthar",
    "Ilam",
    "Jhapa",
    "Morang",
    "Sunsari",
    "Dhankuta",
    "Terhathum",
    "Sankhuwasabha",
    "Bhojpur",
    "Solukhumbu",
    "Okhaldhunga",
    "Khotang",
    "Udayapur",
  ],
  "2": [
    "Saptari",
    "Siraha",
    "Dhanusa",
    "Mahottari",
    "Sarlahi",
    "Rautahat",
    "Bara",
    "Parsa",
  ],
  "3": [
    "Dolakha",
    "Sindhupalchok",
    "Rasuwa",
    "Dhading",
    "Nuwakot",
    "Kathmandu",
    "Bhaktapur",
    "Lalitpur",
    "Kavrepalanchok",
    "Ramechhap",
    "Sindhuli",
    "Makwanpur",
    "Chitwan",
  ],
  "4": [
    "Gorkha",
    "Manang",
    "Mustang",
    "Myagdi",
    "Kaski",
    "Lamjung",
    "Tanahu",
    "Nawalparasi East",
    "Syangja",
    "Parbat",
    "Baglung",
  ],
  "5": [
    "Rukum East",
    "Rolpa",
    "Pyuthan",
    "Gulmi",
    "Arghakhanchi",
    "Palpa",
    "Nawalparasi West",
    "Rupandehi",
    "Kapilvastu",
    "Dang",
    "Banke",
    "Bardiya",
  ],
  "6": [
    "Dolpa",
    "Mugu",
    "Humla",
    "Jumla",
    "Kalikot",
    "Dailekh",
    "Jajarkot",
    "Rukum West",
    "Salyan",
    "Surkhet",
  ],
  "7": [
    "Bajura",
    "Bajhang",
    "Darchula",
    "Baitadi",
    "Dadeldhura",
    "Doti",
    "Achham",
    "Kailali",
    "Kanchanpur",
  ],
};

// Localities by district (expanded for more districts)
export const localitiesByDistrict: Record<string, string[]> = {
  // Bagmati Province
  Kathmandu: [
    "Thamel",
    "Baluwatar",
    "Lazimpat",
    "Baneshwor",
    "Kalanki",
    "Chabahil",
    "Bouddha",
    "Jorpati",
    "Gongabu",
    "Kirtipur",
    "Budhanilkantha",
    "Swayambhu",
    "Kalimati",
    "Balaju",
    "Maharajgunj",
    "Naxal",
    "Putalisadak",
    "Sundhara",
    "New Road",
    "Asan",
    "Dillibazar",
    "Jamal",
    "Tripureshwor",
    "Kupondole",
  ],
  Lalitpur: [
    "Jawalakhel",
    "Kupondole",
    "Pulchowk",
    "Sanepa",
    "Jhamsikhel",
    "Lagankhel",
    "Satdobato",
    "Imadol",
    "Dhapakhel",
    "Mangalbazar",
    "Chakupat",
    "Nakkhu",
    "Sunakothi",
    "Lubhu",
    "Godavari",
  ],
  Bhaktapur: [
    "Suryabinayak",
    "Lokanthali",
    "Katunje",
    "Thimi",
    "Dadhikot",
    "Balkot",
    "Jhaukhel",
    "Durbar Square",
    "Byasi",
    "Changunarayan",
    "Nagarkot",
  ],
  Chitwan: [
    "Bharatpur",
    "Narayangarh",
    "Ratnanagar",
    "Khairahani",
    "Madi",
    "Meghauli",
    "Patihani",
    "Gitanagar",
    "Shivanagar",
  ],

  // Gandaki Province
  Kaski: [
    "Lakeside",
    "Baidam",
    "Chipledhunga",
    "Mahendrapool",
    "Birauta",
    "Hemja",
    "Sarangkot",
    "Simalchaur",
    "Lamachaur",
    "Pardi",
    "Malepatan",
    "Rambazar",
    "Srijana Chowk",
    "Prithvi Chowk",
  ],

  // Koshi Province
  Morang: [
    "Biratnagar",
    "Urlabari",
    "Pathari",
    "Belbari",
    "Rangeli",
    "Letang",
    "Sundarharaicha",
    "Itahara",
  ],
  Jhapa: [
    "Birtamod",
    "Damak",
    "Bhadrapur",
    "Mechinagar",
    "Arjundhara",
    "Kankai",
    "Shivasatakshi",
    "Gauradaha",
    "Gaurigunj",
  ],
  Sunsari: [
    "Dharan",
    "Itahari",
    "Inaruwa",
    "Duhabi",
    "Barahachhetra",
    "Ramdhuni",
    "Koshi",
    "Gadhi",
    "Harinagara",
  ],

  // Madhesh Province
  Parsa: [
    "Birgunj",
    "Pokhariya",
    "Parsagadhi",
    "Bahudarmai",
    "Bindabasini",
    "Dhobini",
    "Jagarnathpur",
  ],
  Bara: [
    "Kalaiya",
    "Jeetpur Simara",
    "Kolhabi",
    "Nijgadh",
    "Mahagadhimai",
    "Simraungadh",
    "Pacharauta",
  ],

  // Lumbini Province
  Rupandehi: [
    "Butwal",
    "Siddharthanagar",
    "Lumbini",
    "Tilottama",
    "Devdaha",
    "Sainamaina",
    "Gaidahawa",
    "Omsatiya",
  ],
  Banke: [
    "Nepalgunj",
    "Kohalpur",
    "Baijanath",
    "Rapti Sonari",
    "Narainapur",
    "Duduwa",
    "Janaki",
  ],

  // Karnali Province
  Surkhet: [
    "Birendranagar",
    "Bheriganga",
    "Gurbhakot",
    "Panchapuri",
    "Chaukune",
    "Barahatal",
    "Simta",
  ],

  // Sudurpashchim Province
  Kailali: [
    "Dhangadhi",
    "Tikapur",
    "Lamki Chuha",
    "Ghodaghodi",
    "Bhajani",
    "Gauriganga",
    "Godawari",
    "Kailari",
  ],
  Kanchanpur: [
    "Bhimdatta",
    "Punarbas",
    "Bedkot",
    "Shuklaphanta",
    "Krishnapur",
    "Belauri",
    "Laljhadi",
  ],
};
